# Generated by Django 2.2 on 2019-05-08 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20190508_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='admin1',
        ),
        migrations.AddField(
            model_name='asset',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='assets.User', verbose_name='资产管理员'),
        ),
    ]
